boundless/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth import views as auth_views
from core import views as core_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", core_views.home, name="home"),
    path("", include("core.urls")),
    path("login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="home"), name="logout"),
    path('signup/', core_views.signup, name='signup'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
# Copyright (C) 2025 TG11
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

import logging
logger = logging.getLogger(__name__)

app_name = "core"

urlpatterns = [
    path("servers/", views.server_list, name="server_list"),
    path("servers/join/<str:code>/", views.join_server, name="join_server"),
    path('servers/create/', views.create_server, name='create_server'),
    path('servers/discover/', views.discover_community_servers, name='discover_community'),
    path("servers/<uuid:server_id>/", views.server_detail, name="server_detail"),
    path('servers/<uuid:server_id>/roles/', views.roles_list, name='roles_list'),
    path('servers/<uuid:server_id>/roles/create/', views.create_role, name='create_role'),
    path('servers/<uuid:server_id>/roles/<uuid:role_id>/edit/', views.edit_role, name='edit_role'),
    path('servers/<uuid:server_id>/roles/<uuid:role_id>/assign/', views.assign_role, name='assign_role'),
    path('servers/<uuid:server_id>/create_channel/', views.create_channel, name='create_channel'),
    path('servers/<uuid:server_id>/create_category/', views.create_category, name='create_category'),
    path('servers/<uuid:server_id>/settings/', views.server_settings, name='server_settings'),
    path("servers/<uuid:server_id>/<uuid:category_id>/", views.category_detail, name="category_detail",),
    path('servers/<uuid:server_id>/<uuid:category_id>/create_channel/', views.create_channel, name='create_channel'),
    path("servers/<uuid:server_id>/<uuid:category_id>/<uuid:channel_id>/", views.channel_detail,name="channel_detail",),
    path("servers/<uuid:server_id>/<uuid:category_id>/<uuid:channel_id>/<uuid:message_id>/edit/", views.edit_message, name="edit_message"),
    path("servers/<uuid:server_id>/<uuid:category_id>/<uuid:channel_id>/<uuid:message_id>/delete/", views.delete_message, name="delete_message"),
    path('servers/<uuid:server_id>/<uuid:category_id>/<uuid:channel_id>/<uuid:message_id>/history/', views.message_history, name='message_history',),
    path("profile/", views.profile, name="profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("profile/<uuid:user_id>/", views.profile, name="profile"),
    path("profile/<uuid:user_id>/send_request/", views.send_friend_request, name="send_friend_request"),
    path("profile/<uuid:user_id>/requests/", views.friend_requests, name="friend_requests"),
    path("profile/<uuid:user_id>/friends/", views.friends_list, name="friends_list"),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='core/auth/password_reset.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='core/auth/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='core/auth/password_reset_form.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='core/auth/password_reset_done.html'), name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/core/server/category/channel/channel_detail.html
<!--
 Copyright (C) 2025 TG11
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as
 published by the Free Software Foundation, either version 3 of the
 License, or (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.
 
 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->

{% extends 'base.html' %}

{% block content %}
  <h2>
    <a href="{% url 'core:server_detail' server_id=server.id %}"><b>{{ server.name }}</b></a> -
    <a href="{% url 'core:category_detail' server_id=server.id category_id=category.id %}"><b>{{ category.name }}</b></a> -
    {{ channel.name }}
  </h2>
  {% if channel.channel_type == "voice" %}
    <iframe
      src="http://172.105.155.247:8080/{{ channel.id }}"
      style="width: 100%; height: 500px; border: 0;"
      allow="camera; microphone; fullscreen; display-capture"
    ></iframe>
  {% else %}
    <ul id="messages">
      {% for message in messages %}
        {% if not message.deleted or user.is_superuser or user.is_staff %}
          <li>
            <strong><img src="{{ message.sender.avatar_or_random }}" style="width: 16px; height: 16px;" class="avatar"><a href="{% url 'core:profile' user_id=message.sender.id %}">{{ message.sender.username }}</a></strong>: {{ message.content }}
            {% if message.sender == user %}
              <a href="{% url 'core:edit_message' server_id=server.id category_id=category.id channel_id=channel.id message_id=message.id %}"><i class="fas fa-edit"></i></a>
              <a href="{% url 'core:delete_message' server_id=server.id category_id=category.id channel_id=channel.id message_id=message.id %}"><i class="fas fa-trash"></i></a>
            {% endif %}
            {% if message.deleted %}
              <span style="color: {{ theme.deleted_color }};">(Deleted)</span>
            {% endif %}
          </li>
        {% endif %}
      {% endfor %}
    </ul>

    <form id="message-form" method="post">
      {% csrf_token %}
      <input type="text" name="content" placeholder="Type your message...">
      <button type="submit">Send</button>
    </form>

    <!-- Add the WebSocket script here -->
    <script>
      const wsScheme = window.location.protocol === "https:" ? "wss" : "ws";
      const chatSocket = new WebSocket(
        wsScheme + '://' + window.location.host +
        '/ws/servers/{{ server.id }}/{{ category.id }}/{{ channel.id }}/'
      );

      chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        const messagesDiv = document.getElementById('messages');
        const li = document.createElement('li');
        li.innerHTML = `<strong>${data.user}</strong>: ${data.message}`;
        messagesDiv.appendChild(li);
      };

      chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
      };

      document.getElementById('message-form').onsubmit = function(e) {
        e.preventDefault();
        const messageInputDom = document.querySelector('input[name="content"]');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
          'message': message
        }));
        messageInputDom.value = '';
      };
    </script>
  {% endif %}
{% endblock %}

templates/core/server/category/channel/create_channel.html
<!--
 Copyright (C) 2025 TG11
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as
 published by the Free Software Foundation, either version 3 of the
 License, or (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.
 
 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->

{% extends 'base.html' %}

{% block content %}
  <h2>Create Channel</h2>
  <form method="post">
    {% csrf_token %}
    <label>Name:</label><input type="text" name="name" required><br>
    <label>Category:</label>
    <select name="category_id">
      {% for cat in categories %}
        <option value="{{ cat.id }}"
        {% if cat.id|stringformat:"s" == selected_category|stringformat:"s" %}selected{% endif %}
        >{{ cat.name }}</option>
      {% endfor %}
    </select><br>
    <label>Type:</label>
    <select name="channel_type" required>
        <option value="text">Text</option>
        <option value="voice">Voice</option>
        <option value="video">Video</option>
        <option value="media">Media</option>
        <option value="forum">Forum</option>
        <option value="announcement">Announcement</option>
        <option value="event">Event</option>
        <option value="support">Support</option>
        <option value="ticket">Ticket</option>
    </select><br>
    <button type="submit">Create Channel</button>
  </form>
  <a href="{% url 'core:server_detail' server_id=server.id %}">Back to Server</a>
{% endblock %}