boundless/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth import views as auth_views
from core import views as core_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", core_views.home, name="home"),
    path("", include("core.urls")),
    path("login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="home"), name="logout"),
    path('signup/', core_views.signup, name='signup'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
# Copyright (C) 2025 TG11
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

import logging
logger = logging.getLogger(__name__)

app_name = "core"

urlpatterns = [
    path("servers/", views.server_list, name="server_list"),
    path("servers/join/<str:code>/", views.join_server, name="join_server"),
    path('servers/create/', views.create_server, name='create_server'),
    path('servers/discover/', views.discover_community_servers, name='discover_community'),
    path("servers/<uuid:server_id>/", views.server_detail, name="server_detail"),
    path('servers/<uuid:server_id>/roles/', views.roles_list, name='roles_list'),
    path('servers/<uuid:server_id>/roles/create/', views.create_role, name='create_role'),
    path('servers/<uuid:server_id>/roles/<uuid:role_id>/edit/', views.edit_role, name='edit_role'),
    path('servers/<uuid:server_id>/roles/<uuid:role_id>/assign/', views.assign_role, name='assign_role'),
    path('servers/<uuid:server_id>/create_channel/', views.create_channel, name='create_channel'),
    path('servers/<uuid:server_id>/create_category/', views.create_category, name='create_category'),
    path('servers/<uuid:server_id>/settings/', views.server_settings, name='server_settings'),
    path("servers/<uuid:server_id>/<uuid:category_id>/", views.category_detail, name="category_detail",),
    path('servers/<uuid:server_id>/<uuid:category_id>/create_channel/', views.create_channel, name='create_channel'),
    path("servers/<uuid:server_id>/<uuid:category_id>/<uuid:channel_id>/", views.channel_detail,name="channel_detail",),
    path("servers/<uuid:server_id>/<uuid:category_id>/<uuid:channel_id>/<uuid:message_id>/edit/", views.edit_message, name="edit_message"),
    path("servers/<uuid:server_id>/<uuid:category_id>/<uuid:channel_id>/<uuid:message_id>/delete/", views.delete_message, name="delete_message"),
    path('servers/<uuid:server_id>/<uuid:category_id>/<uuid:channel_id>/<uuid:message_id>/history/', views.message_history, name='message_history',),
    path("profile/", views.profile, name="profile"),
    path("profile/edit/", views.edit_profile, name="edit_profile"),
    path("profile/<uuid:user_id>/", views.profile, name="profile"),
    path("profile/<uuid:user_id>/send_request/", views.send_friend_request, name="send_friend_request"),
    path("profile/<uuid:user_id>/requests/", views.friend_requests, name="friend_requests"),
    path("profile/<uuid:user_id>/friends/", views.friends_list, name="friends_list"),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='core/auth/password_reset.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='core/auth/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='core/auth/password_reset_form.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='core/auth/password_reset_done.html'), name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/forms.py
# Copyright (C) 2025 TG11
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Server

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(required=False)
    display_name = forms.CharField(max_length=100, required=False)
    bio = forms.CharField(widget=forms.Textarea, required=False)
    avatar = forms.ImageField(required=False)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            "username",
            "password1",
            "password2",
            "first_name",
            "last_name",
            "email",
            "display_name",
            "bio",
            "avatar",
        )


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "display_name",
            "first_name",
            "last_name",
            "email",
            "bio",
            "avatar",
            "phone_number",
            "show_email",
            "show_legal_name",
            "show_phone_number",
            "show_bio",
            "show_avatar",
        ]


class ServerSettingsForm(forms.ModelForm):
    class Meta:
        model = Server
        fields = ["name", "description", "community", "icon"]

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Server, Channel, Message, User, FriendRequest, Category, MessageEditHistory, Role
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm, ProfileEditForm, ServerSettingsForm
from django.http import HttpResponseForbidden
import uuid
from django.core.exceptions import ValidationError, PermissionDenied
import logging
from django import forms
from django.utils import timezone
logger = logging.getLogger(__name__)

# Create your views here.


def home(request):
    return render(request, "home.html")


@login_required
def server_list(request):
    # servers = Server.objects.all()
    servers = request.user.servers.all()  # Only servers the user is a member of
    return render(request, "core/server/servers.html", {"servers": servers})


@login_required
def discover_community_servers(request):
    servers = Server.objects.filter(community=True).exclude(members=request.user)
    return render(request, "core/server/discover_community.html", {"servers": servers})


@login_required
def server_detail(request, server_id):
    server = get_object_or_404(Server, id=server_id)
    # Check if user is a member or if community=True
    if not server.community and request.user not in server.members.all():
        return PermissionDenied("You do not have access to this server.")
    categories = server.categories.prefetch_related("channels").all()
    user_roles = server.roles.filter(users=request.user)
    channels = server.channels.filter(allowed_roles__in=user_roles).distinct()
    user = request.user

    if request.method == "POST" and user in server.members.all():
        # Use the first channel as default for sending
        channel = channels.first()
        Message.objects.create(
            sender=user, channel=channel, content=request.POST["content"]
        )

    return render(
        request,
        "core/server/server_detail.html",
        {
            "server": server,
            "categories": categories,
            "channels": channels,  # Optional: if you want to show non-categorized channels separately
        },
    )


@login_required
def join_server(request, code):
    server = get_object_or_404(Server, join_code=code)
    server.members.add(request.user)
    everyone_role = server.roles.get(name="@everyone")
    everyone_role.users.add(request.user)
    return redirect("core:server_detail", server_id=server.id)


@login_required
def send_friend_request(request, user_id):
    from_user = request.user
    to_user = get_object_or_404(User, id=user_id)

    if from_user != to_user and not FriendRequest.objects.filter(from_user=from_user, to_user=to_user).exists():
        FriendRequest.objects.create(from_user=from_user, to_user=to_user)

    return redirect("core:profile", user_id=to_user.id)


@login_required
def accept_friend_request(request, request_id):
    friend_request = get_object_or_404(
        FriendRequest, id=request_id, to_user=request.user
    )
    friend_request.status = "accepted"
    friend_request.save()
    request.user.friends.add(friend_request.from_user)
    friend_request.from_user.friends.add(request.user)
    return redirect("core:profile", user_id=friend_request.from_user.id)


@login_required
def decline_friend_request(request, request_id):
    friend_request = get_object_or_404(
        FriendRequest, id=request_id, to_user=request.user
    )
    friend_request.delete()
    return redirect("core:profile", user_id=friend_request.from_user.id)


@login_required
def profile(request, user_id=None):
    if user_id:
        try:
            user_profile = User.objects.get(id=user_id)
        except (ValueError, ValidationError, User.DoesNotExist):
            return render(request, "core/errors/user_not_found.html", status=404)
    else:
        user_profile = request.user

    shared_servers = request.user.shared_servers_with(user_profile)
    shared_friends = request.user.shared_friends_with(user_profile)
    friend_requests = FriendRequest.objects.filter(
        to_user=request.user, status="pending"
    )

    return render(
        request,
        "core/profile/profile.html",
        {
            "user_profile": user_profile,
            "shared_servers": shared_servers,
            "shared_friends": shared_friends,
            "friend_requests": friend_requests,
        },
    )


@login_required
def edit_profile(request):
    if request.method == "POST":
        form = ProfileEditForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("core:profile")
    else:
        form = ProfileEditForm(instance=request.user)
    return render(request, "core/profile/edit_profile.html", {"form": form})


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.first_name = form.cleaned_data.get("first_name")
            user.last_name = form.cleaned_data.get("last_name")
            user.email = form.cleaned_data.get("email")
            user.display_name = form.cleaned_data.get("display_name")
            user.bio = form.cleaned_data.get("bio")
            if form.cleaned_data.get("avatar"):
                user.avatar = form.cleaned_data.get("avatar")
            user.save()

            from django.contrib.auth import login

            login(request, user)
            return redirect("home")
    else:
        form = CustomUserCreationForm()
    return render(request, "signup.html", {"form": form})


def theme_preview(request):
    themes = ["dark", "light", "orange", "synth"]
    return render(request, "themes/preview.html", {"themes": themes})


class ServerCreationForm(forms.ModelForm):
    community = forms.BooleanField(required=False, initial=False, label="Public (Community Server)?")

    class Meta:
        model = Server
        fields = ["name", "description", "icon", "community"]


@login_required
def create_server(request):
    if request.method == "POST":
        form = ServerCreationForm(request.POST, request.FILES)
        if form.is_valid():
            server = form.save(commit=False)
            server.owner = request.user
            server.save()
            server.members.add(request.user)  # Add owner as first member

            # Create default category
            uncategorized = Category.objects.create(server=server, name="Uncategorized", protected=True)

            # Create default "general" channel
            Channel.objects.create(
                server=server,
                name="general",
                channel_type="text",
                category=uncategorized,
            )

            return redirect("core:server_detail", server_id=server.id)
    else:
        form = ServerCreationForm()
    return render(request, "core/server/create_server.html", {"form": form})


class CategoryCreationForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name"]


@login_required
def create_category(request, server_id):
    server = get_object_or_404(Server, id=server_id, owner=request.user)
    if request.method == "POST":
        form = CategoryCreationForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.server = server
            category.save()
            return redirect("core:server_detail", server_id=server.id)
    else:
        form = CategoryCreationForm()
    return render(request, "core/server/category/create_category.html", {"form": form, "server": server})


class ChannelCreationForm(forms.ModelForm):
    class Meta:
        model = Channel
        fields = ["name", "channel_type", "category"]


@login_required
def create_channel(request, server_id, category_id=None):
    server = get_object_or_404(Server, id=server_id, owner=request.user)

    if request.method == "POST":
        # Use manual fields instead of the Django form
        name = request.POST.get("name")
        category_id = request.POST.get("category_id")
        channel_type = request.POST.get("channel_type")
        category = Category.objects.filter(id=category_id, server=server).first()

        Channel.objects.create(
            name=name,
            server=server,
            category=category,  # might be None if no category chosen
            channel_type=channel_type,
        )
        return redirect("core:server_detail", server_id=server.id)

    # Load categories for dropdown
    categories = server.categories.all()
    return render(request, "core/server/category/channel/create_channel.html", {"server": server, "categories": categories, "selected_category": category_id})


@login_required
def channel_detail(request, server_id, category_id, channel_id):
    server = get_object_or_404(Server, id=server_id)
    category = get_object_or_404(Category, id=category_id, server=server)
    channel = get_object_or_404(
        Channel, id=channel_id, server=server, category=category
    )

    if request.method == "POST" and request.user in server.members.all():
        Message.objects.create(
            sender=request.user, channel=channel, content=request.POST["content"]
        )
        return redirect(
            "core:channel_detail",
            server_id=server.id,
            category_id=category.id,
            channel_id=channel.id,
        )

    messages = channel.messages.order_by("created_at")
    return render(
        request,
        "core/server/category/channel/channel_detail.html",
        {
            "server": server,
            "category": category,
            "channel": channel,
            "messages": messages,
            "user": request.user,
        },
    )


@login_required
def category_detail(request, server_id, category_id):

templates/core/server/create_server.html
<!--
 Copyright (C) 2025 TG11
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as
 published by the Free Software Foundation, either version 3 of the
 License, or (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.
 
 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->

{% extends 'base.html' %}

{% block content %}
  <h2>Create Server</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
  </form>
{% endblock %}

templates/core/server/discover_community.html
<!--
 Copyright (C) 2025 TG11
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as
 published by the Free Software Foundation, either version 3 of the
 License, or (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.
 
 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->

{% extends 'base.html' %}

{% block content %}
  <h2>Discover Community Servers</h2>
  <ul>
    {% for server in servers %}
      <li>
        {{ server.name }} -
        <a href="{% url 'core:join_server' code=server.join_code %}">Join</a>
      </li>
    {% empty %}
      <li>No community servers to discover!</li>
    {% endfor %}
  </ul>
  <a href="{% url 'core:server_list' %}">Back to My Servers</a>
{% endblock %}

templates/core/server/server_detail.html
<!--
 Copyright (C) 2025 TG11
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as
 published by the Free Software Foundation, either version 3 of the
 License, or (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.
 
 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->

{% extends 'base.html' %}
{% block content %}
<img src="{{ server.icon_or_random }}" alt="{{ server.name }} Icon" style='width: 2vw; height: 2vw;'><h1>{{ server.name }}</h1>
<p>{{ server.description }}</p>
<a href="{% url 'core:create_category' server_id=server.id %}"><button>Create Category</button></a>


<div class="sidebar">
  <h2>{{ server.name }}</h2>
  {% for category in server.categories.all %}
    <details>
      <summary><a href="{% url 'core:category_detail' server_id=server.id category_id=category.id %}">{{ category.name }}</a></summary>
      <ul>
        {% for channel in category.channels.all %}
          <li>
            <a href="{% url 'core:channel_detail' server_id=server.id category_id=category.id channel_id=channel.id %}">
              {{ channel.name }}
            </a>
          </li>
        {% endfor %}
      </ul>
    </details>
  {% endfor %}
</div>




<a href="{% url 'core:server_list' %}">Back to Servers</a>
{% endblock %}

{% if user in server.members.all %}
  <form method="post">
    {% csrf_token %}
    <textarea name="content"></textarea>
    <button type="submit">Send</button>
  </form>
{% endif %}

templates/core/server/server_settings.html
<!--
 Copyright (C) 2025 TG11
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as
 published by the Free Software Foundation, either version 3 of the
 License, or (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.
 
 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->

{% extends 'base.html' %}
{% block content %}
<h2>Edit Server Settings - {{ server.name }}</h2>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>
<a href="{% url 'core:server_detail' server_id=server.id %}">Back</a>
{% endblock %}

templates/core/server/servers.html
<!--
 Copyright (C) 2025 TG11
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as
 published by the Free Software Foundation, either version 3 of the
 License, or (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.
 
 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->

{% extends 'base.html' %}
{% block content %}
<a href="{% url 'core:create_server' %}"><button>Create Server</button></a> <a href="{% url 'core:discover_community' %}"><button>Community (Public) Servers</button></a>
<h2>Servers List</h2>

<div class="server-grid flex items-start gap-4 rounded p-4 shadow hover:bg-zinc-700 transition">
  {% for server in servers %}
    <div class="server-card">
      <img src="{{ server.icon_or_random }}" class="server-icon w-12 h-12 rounded object-cover border border-zinc-600" style="width:64px; height:64px;">
      <div class="server-info flex items-center gap-2">
        <h1 class="font-semibold hover:underline">{% if server.owner == user %}<i class="fa-solid fa-crown"></i>{% endif %}<a href="{% url 'core:server_detail' server.id %}">{{ server.name }}</a></h1>
        <br>
        <p class="text-sm mt-1">{{ server.description }}</p>
        <br>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

templates/core/server/test_server_detail.html
<!--
 Copyright (C) 2025 TG11
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as
 published by the Free Software Foundation, either version 3 of the
 License, or (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.
 
 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->
{% extends 'base.html' %}
{% block content %}
<div class="grid grid-cols-[250px_1fr] grid-rows-[auto_1fr] h-screen">

  <!-- Sidebar: Server + Categories + Channels -->
  <aside class="bg-surface text-text border-r border-input-border p-4 overflow-y-auto">
    <div class="flex items-center gap-3 mb-4">
      <img src="{{ server.icon.url }}" class="rounded-full object-cover" alt="{{ server.name }}" style='width: 1vw; height: 1vw;'>
      <h2 class="text-lg font-semibold">{{ server.name }}</h2>
    </div>
    {% for category in categories %}
      <div class="mb-2">
        <h3 class="text-sm text-accent font-bold uppercase tracking-wide">{{ category.name }}</h3>
        <ul class="pl-3 mt-1 space-y-1">
          {% for channel in category.channels.all %}
            <li>
              <a href="{% url 'core:channel_detail' server_id=server.id category_id=category.id channel_id=channel.id %}"
                 class="block text-sm hover:text-accent {% if channel.id == active_channel.id %}font-bold{% endif %}">
                # {{ channel.name }}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    {% endfor %}
  </aside>

  <!-- Topbar (optional for server tools or breadcrumbs) -->
  <header class="col-span-2 bg-header-bg text-text p-3 flex justify-between items-center border-b border-input-border">
    <h1 class="text-lg font-semibold"># {{ active_channel.name }}</h1>
    <!-- Optional buttons: settings, theme selector, etc. -->
  </header>

  <!-- Main Content: Messages -->
  <main class="col-span-1 overflow-y-auto bg-base text-text p-4 space-y-4">
    {% for message in messages %}
      <div class="flex items-start gap-3">
        <img src="{{ message.sender.profile.avatar.url }}" class="w-8 h-8 rounded-full object-cover">
        <div>
          <p class="font-semibold text-sm">{{ message.sender.username }}</p>
          <p class="text-sm">{{ message.content }}</p>
        </div>
      </div>
    {% endfor %}
  </main>

  <!-- Optional: Right Sidebar for Members or Thread Info 

  <aside class="hidden lg:block bg-surface text-text border-l border-input-border p-4">
    Members panel, thread info, etc.
  </aside>
-->


</div>
{% endblock %}